---
# Testing overwriting C colors
C:
  extensions:
    - ".c"

  default_color: "#24292e"
  comment_color: "#969896"
  id_color: "#7b9c0e"
  number_color: "#745296"
  string_color: "#8B9EB7"

  comment:
    - single_line: "//"
    - begin_multiline: "/*"
    - end_multiline: "*/"

  grammar:
    - color: "#a71d5d"
      keywords:
        - "include"
        - "void"
        - "int"
        - "float"

    - color: "#FF1053"
      keywords:
        - "printf"
        - "putchar"
        - "getchar"

# Including a complete new language
Brain:
  extensions:
    - ".br"
    - ".brain"
  
  default_color: "#969896"

  grammar:
    - color: "#a71d5d"
      operators:
        - ">"
        - "<"
        - "^"
        - "&lt;"
        - "&gt;"

    - color: "#333333"
      operators:
        - "["
        - "]"
        - "{"
        - "}"
        - "?"
        - ":"
        - ";"
        - "!"

    - color: "#0086b3"
      operators:
        - "+"
        - "-"
        - "*"
        - "/"
        - "%"
        - "_"

    - color: "#795da3"
      operators:
        - "."
        - ","
        - "$"
        - "#"

# Overwriting BF - Testing GitHub known languages
Brainfuck:
  extensions:
    - ".bf"

  grammar:
    - color: "#BF211E"
      operators:
        - ">"
        - "<"
        - "&lt;"
        - "&gt;"

    - color: "#B744B8"
      operators:
        - "["
        - "]"

    - color: "#69A197"
      operators:
        - "+"
        - "-"

    - color: "#F9DC5C"
      operators:
        - "."
        - ","

# Testing Regex and others
Test:
  extensions:
    - ".test"
  
  default_color: "#FF8272"
  comment_color: "#969896"
  id_color: "#FF99FF"
  number_color: "#FF6600"
  string_color: "#333300"
  
  comment:
    - single_line: "//"
    - begin_multiline: "/*"
    - end_multiline: "*/"

  grammar:
    - color: "#72EEBB"
      keywords:
        - "for"
        - "while"
      regexes:
        - regex: "(&|amp;)\/[^\/]*\/[gmixXsuUAJD]*"
          modifier: ""

    - color: "#FF00FF"
      keywords:
        - "if"
        - "else"
        - "switch"
        - "let"
