---
# Testing overwriting C colors
AdvPL:
  extensions:
    - ".prw"
    - ".apw"
    - ".aph"
    - ".ch"

  identifier:
    color: "#55B4D4"

  string:
    color: "#86B300"

  number:
    color: "#A37ACC"

  comment:
    color: "#969896"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#86B300"
      operators:
        - "#"
      keywords:
        - "include"

    - color: "#FA6E32"
      keywords:
        - "Static"
        - "Function"
        - "Local"
        - "Return"
        - "If"
        - "Else"
        - "EndIf"

    - color: "#6E7580"
      operators:
        - "@"
        - "=="
        - ":="
        - ":"
        - "("
        - ")"
        - "["
        - "]"

C:
  extensions:
    - ".c"

  default:
    color: "#24292e"

  identifier:
    color: "#7b9c0e"

  number:
    color: "#745296"

  string:
    color: "#8B9EB7"

  comment:
    color: "#969896"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "include"
        - "void"
        - "int"
        - "float"

    - color: "#FF1053"
      keywords:
        - "printf"
        - "putchar"
        - "getchar"

# Including a complete new language
Brain:
  extensions:
    - ".br"
    - ".brain"
  
  default:
    color: "#969896"

  group:
    - color: "#a71d5d"
      operators:
        - ">"
        - "<"
        - "^"
        - "&lt;"
        - "&gt;"

    - color: "#333333"
      operators:
        - "["
        - "]"
        - "{"
        - "}"
        - "?"
        - ":"
        - ";"
        - "!"

    - color: "#0086b3"
      operators:
        - "+"
        - "-"
        - "*"
        - "/"
        - "%"
        - "_"

    - color: "#795da3"
      operators:
        - "."
        - ","
        - "$"
        - "#"

# Overwriting BF - Testing GitHub known languages
Brainfuck:
  extensions:
    - ".bf"

  group:
    - color: "#BF211E"
      operators:
        - ">"
        - "<"
        - "&lt;"
        - "&gt;"

    - color: "#B744B8"
      operators:
        - "["
        - "]"

    - color: "#69A197"
      operators:
        - "+"
        - "-"

    - color: "#F9DC5C"
      operators:
        - "."
        - ","

Siren:
  extensions:
    - ".siren"

  default:
    color: "#d33682"

  string:
    color: "#dc322f"

  number:
    color: "#2aa198"

  identifier:
    color: "#b58900"

  comment:
    color: "#969896"
    single_line: "#"

  group:
    - color: "#268bd2"
      keywords:
        - "True"
        - "False"

    - color: "#002b36"
      keywords:
        - "def"
        - "let"

    - color: "#FF8272"
      keywords:
        - "self"
      regexes:
        - regex: "@(lazy)"
          modifier: ""
        - regex: "\\$siren\/\\d+"
          modifier: ""

# Testing Regex and others
Test:
  extensions:
    - ".test"
 
  default:
    color: "#FF8272"

  identifier:
    color: "#FF99FF"

  number:
    color: "#FF6600"
 
  string:
    color: "#333300"
 
  comment:
    color: "#969896"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#72EEBB"
      keywords:
        - "for"
        - "while"
      regexes:
        - regex: "(&|amp;)\/[^\/]*\/[gmixXsuUAJD]*"
          modifier: ""

    - color: "#FF00FF"
      keywords:
        - "if"
        - "else"
        - "switch"
        - "let"

