---
Brain:
  extensions:
    - ".br"
    - ".brain"
  default_color: "#969896"
  
  grammar:
    - color: "#a71d5d"
      operators:
        - ">"
        - "<"
        - "^"
        - "&lt;"
        - "&gt;"
        
    - color: "#333333"
      operators:
        - "["
        - "]"
        - "{"
        - "}"
        - "?"
        - ":"
        - ";"
        - "!"
        
    - color: "#0086b3"
      operators:
        - "+"
        - "-"
        - "*"
        - "/"
        - "%"
        - "_"
    
    - color: "#795da3"
      operators:
        - "."
        - ","
        - "$"
        - "#"
Test:
  extensions:
    - ".test"
  default_color: "#FF8272"
  comment_color: "#969896"
  id_color: "#FF99FF"
  number_color: "#FF6600"
  string_color: "#333300"
  single_line_comment: "//"
  begin_multiline_comment: "/*"
  end_multiline_comment: "*/"
  
  grammar:
    - color: "#72EEBB"
      keywords:
        - "for"
        - "while"
      regexes:
        - regex: "&(amp;)\/[^\/]*\/([\\S]?)*"
          modifier: ""
    
    - color: "#FF00FF"
      keywords:
        - "if"
        - "else"
        - "switch"
        - "let"

