language: node_js
node_js:
  - "7"
  - "6"

#  JSDOM does not run on versions 5 and 4 :(
#  - "5"
#  - "4"

cache:
  directories:
    - "node_modules"

before_script:
  - "npm install mocha"
  - "npm install should"
  - "npm install xmlhttprequest"
  - "npm install jsdom"

script:
  - "npm test"

